# Generated by Django 5.1.1 on 2024-09-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='student_id',
        ),
    ]
