# Generated by Django 5.1.1 on 2024-11-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_user_last_login_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='room',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='time',
        ),
    ]
